In [1]:
import numpy as np


In [2]:
numbers = np.array([1,2,3,4,5])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([1, 2, 3, 4, 5])

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
num = [x for x in range (21) if x%2 ==0]


In [7]:
print(num)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [8]:
num = [x for x in range (2,21,2)]


In [9]:
print(num)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [12]:
integers = np.array([[1,2,3,],[4,5,6]])

print(integers)

[[1 2 3]
 [4 5 6]]


In [13]:
integers.ndim

2

In [14]:
numbers.ndim

1

In [16]:
integers.shape

(2, 3)

In [18]:
numbers.shape

(5,)

In [19]:
integers.size

6

In [20]:
integers.itemsize

8

In [21]:
for row in integers:
    for column in row:
        print(column, end = ' ')
    print()

1 2 3 
4 5 6 


In [23]:
for i in integers.flat:
    print(i, end = ' ')

1 2 3 4 5 6 

---------------------------------FUNCTION CALLBACK-----------------------


In [6]:
import time
def finished_cooking():
    print("ding dong finished cooking")

In [11]:
def cooking(action):
    print("cooking food for my wife")
   
    for i in range(int(time.sleep(2)),-1):
        print(i,end = "\r")
    action()

In [12]:
cooking(finished_cooking)

cooking food for my wife


TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [15]:
import time

def finished_cooking():
    print("Ding dong! Finished cooking 🍲")

def cooking(action):
    print("Cooking food for my wife...")

    # countdown from 5 to 0
    for i in range(5, -1, -1):   # start at 5, stop at -1
        print(f"Time left: {i}", end="\r")  
        time.sleep(1)  # wait 1 second each time

    print()  # move to next line after countdown
    action() # call the callback

cooking(finished_cooking)


Cooking food for my wife...
Time left: 0
Ding dong! Finished cooking 🍲


In [16]:
import time

def finished_cooking():
    print("Ding dong! Finished cooking 🍲")

def cooking(action):
    print("Cooking food for my wife...")
    for i in range(5, -1, -1):
        print(f"\033[KTime left: {i}", end="\r")
        time.sleep(1)
    print()
    action()

cooking(finished_cooking)


Cooking food for my wife...
Time left: 0
Ding dong! Finished cooking 🍲


In [17]:
np.arrange(5)

NameError: name 'np' is not defined

In [18]:
import np


ModuleNotFoundError: No module named 'np'

In [19]:
import numpy as np

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [27]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

It cannot reshape the array if the size doesnot math while mult row and col

In [29]:
np.arange(1,21).reshape(7,2)

ValueError: cannot reshape array of size 20 into shape (7,2)

Now displaying the large no of array


In [30]:
np.arange(1,100001)

array([     1,      2,      3, ...,  99998,  99999, 100000],
      shape=(100000,))

In [31]:
np.arange(1,100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]],
      shape=(4, 25000))

In [32]:
np.arange(1,100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]],
      shape=(100, 1000))

----------- List VS Array performance----------------


In [33]:
import random

In [35]:
%timeit rolls_list = [random.randrange(1,7) for i in range(0, 6000000)]

1.11 s ± 4.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
%timeit rolls_array = np.random.randint(1,7,6000000)

46 ms ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [38]:
%timeit rolls_array = np.random.randint(1,7,60000000)

389 ms ± 93.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
%timeit rolls_array = np.random.randint(1,7,600000000)

3.73 s ± 132 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Custiomizing %time it to run desired no of run per each loo[p


In [43]:
%timeit -n3 -r2 rolls_array = np.random.randint(1,7,6000000)


82.9 ms ± 762 μs per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [45]:
%timeit sum([ x for x in range (1,6000000)])

320 ms ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [47]:
%timeit np.arange(1,10000000).sum()

7.3 ms ± 102 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


_________________ARITHMETIC OPERATION IN ARRAY_____________________


In [57]:
numbers = np.arange(1,6)

In [52]:
numbers

2

In [50]:
numbers = 2

In [51]:
numbers

2

In [55]:
numbers 

array([1, 2, 3, 4, 5])

In [59]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [60]:
numbers **3

array([  1,   8,  27,  64, 125])

In [61]:
numbers

array([1, 2, 3, 4, 5])

In [62]:
numbers += 10

In [63]:
numbers

array([11, 12, 13, 14, 15])

In [75]:
numbers2 = np.linspace(1.1, 5.5, 5) 

In [76]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [77]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [78]:
numbers

array([11, 12, 13, 14, 15])

In [79]:
numbers >= 13

array([False, False,  True,  True,  True])

In [82]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [83]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [84]:
numbers == numbers2

array([False, False, False, False, False])

In [85]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [86]:
grades = np.array([
    [85, 90, 78],
    [92, 88, 79],
    [75, 80, 85],
    [89, 94, 91]
])

In [87]:
grades

array([[85, 90, 78],
       [92, 88, 79],
       [75, 80, 85],
       [89, 94, 91]])

In [88]:
grades.sum()

np.int64(1026)

In [89]:
grades.min()


np.int64(75)

In [91]:
grades.max()

np.int64(94)

In [92]:
grades.mean()

np.float64(85.5)

In [93]:
grades.std()

np.float64(5.937171043518958)

In [94]:
grades.var()

np.float64(35.25)

In [95]:
grades.mean(axis = 0)

array([85.25, 88.  , 83.25])

In [96]:
grades.mean(axis = 1)

array([84.33333333, 86.33333333, 80.        , 91.33333333])

In [97]:
imprt numpy as np

SyntaxError: invalid syntax (3522848920.py, line 1)

In [114]:
import numpy as np

grades =np.random.randint(60,101,12).reshape(3,4)

In [115]:
grades

array([[77, 70, 91, 88],
       [78, 74, 64, 79],
       [99, 76, 92, 73]])

In [116]:
grades.reshape(3,4)

array([[77, 70, 91, 88],
       [78, 74, 64, 79],
       [99, 76, 92, 73]])

In [117]:
grades.mean()

np.float64(80.08333333333333)

In [118]:
grades.mean(axis = 0)


array([84.66666667, 73.33333333, 82.33333333, 80.        ])

In [120]:
grades.mean(axis = 1)

array([81.5 , 73.75, 85.  ])

In [121]:
numbers = np.array([1,4,9,16,25,36])


In [122]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [123]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [124]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [125]:
numbers2 = np.arange(1,7) * 10

In [126]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [128]:
np.add(numbers,numbers2)

array([11, 24, 39, 56, 75, 96])

In [130]:

np.multiply(numbers2,5)

array([ 50, 100, 150, 200, 250, 300])

In [131]:
numbers2



array([10, 20, 30, 40, 50, 60])

In [132]:
numbers2.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [135]:
import numpy as np
import random

grades = np.array([random.randrange(60, 101) for i in range(12)]).reshape(3, 4)
print(grades)


[[90 94 87 61]
 [61 60 87 80]
 [80 96 65 81]]


In [136]:
numbers3 = numbers2.reshape(2,3)

In [137]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [139]:
numbers4 = np.array([2,4,6])

In [140]:
np.multiply(numbers3,numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [141]:
numbers


array([ 1,  4,  9, 16, 25, 36])

In [142]:
np.power(numbers,3)

array([    1,    64,   729,  4096, 15625, 46656])

In [143]:
grades

array([[90, 94, 87, 61],
       [61, 60, 87, 80],
       [80, 96, 65, 81]])

In [144]:
grades[0,1]

np.int64(94)

In [145]:
grades[1]

array([61, 60, 87, 80])

In [146]:
grades[0:2]

array([[90, 94, 87, 61],
       [61, 60, 87, 80]])

In [147]:
grades[1,3]

np.int64(80)

In [148]:
grades[1:3]

array([[61, 60, 87, 80],
       [80, 96, 65, 81]])

In [149]:
grades[:,0]

array([90, 61, 80])

In [150]:
grades[:0]

array([], shape=(0, 4), dtype=int64)

In [151]:
grades[:,(1,3)]

array([[94, 61],
       [60, 80],
       [96, 81]])

In [153]:
grades[:,1:3]


array([[94, 87],
       [60, 87],
       [96, 65]])

___________________SHALLOW COPIES________________________


In [154]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [155]:
numbers2 = numbers.view()

In [156]:
numbers2

array([ 1,  4,  9, 16, 25, 36])

In [157]:
id(numbers)

140193304641232

In [158]:
id(numbers2)

140193167168624

In [159]:
numbers2.copy(numbers3)

TypeError: order must be str, not numpy.ndarray

In [160]:
numbers3 = numbers2.copy()

In [161]:
numbers3


array([ 1,  4,  9, 16, 25, 36])

In [162]:
id(numbers3)

140193167168720

In [165]:
numbers[1] *= 10

In [166]:
numbers

array([ 1, 40,  9, 16, 25, 36])

In [167]:
numbers2

array([ 1, 40,  9, 16, 25, 36])

In [168]:
numbers[1] /= 10

In [169]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [170]:
numbers2

array([ 1,  4,  9, 16, 25, 36])

____________SLICING VIEW_________________

In [171]:
numbers2 = numbers[0:3]


In [172]:
numbers2

array([1, 4, 9])

In [174]:
id(numbers)


140193304641232

In [175]:
id(numbers2)

140193167169776

In [176]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [177]:
numbers[1] *=10

In [178]:
numbers2

array([ 1, 40,  9])

In [179]:
grades

array([[90, 94, 87, 61],
       [61, 60, 87, 80],
       [80, 96, 65, 81]])

In [183]:
grades.reshape(1)

SyntaxError: invalid syntax (2793424820.py, line 1)

In [184]:
grades.reshape(-1)

array([90, 94, 87, 61, 61, 60, 87, 80, 80, 96, 65, 81])

In [185]:
grades

array([[90, 94, 87, 61],
       [61, 60, 87, 80],
       [80, 96, 65, 81]])

In [187]:

flattened = grades.flatten()

In [188]:
flattened

array([90, 94, 87, 61, 61, 60, 87, 80, 80, 96, 65, 81])

In [189]:
grades

array([[90, 94, 87, 61],
       [61, 60, 87, 80],
       [80, 96, 65, 81]])

In [191]:

flattened[0] = 100

In [192]:
flattened

array([100,  94,  87,  61,  61,  60,  87,  80,  80,  96,  65,  81])

In [193]:
raveled = grades.ravel()

In [194]:
grades

array([[90, 94, 87, 61],
       [61, 60, 87, 80],
       [80, 96, 65, 81]])

In [195]:
raveled

array([90, 94, 87, 61, 61, 60, 87, 80, 80, 96, 65, 81])

In [196]:
raveled[0] = 100

In [197]:
raveled

array([100,  94,  87,  61,  61,  60,  87,  80,  80,  96,  65,  81])

In [198]:
grades

array([[100,  94,  87,  61],
       [ 61,  60,  87,  80],
       [ 80,  96,  65,  81]])

In [199]:
grades.T

array([[100,  61,  80],
       [ 94,  60,  96],
       [ 87,  87,  65],
       [ 61,  80,  81]])

In [200]:
grades

array([[100,  94,  87,  61],
       [ 61,  60,  87,  80],
       [ 80,  96,  65,  81]])

In [201]:
np.hstack(grades,grades2)

NameError: name 'grades2' is not defined

In [202]:
grades2

NameError: name 'grades2' is not defined

In [203]:
grades2 = np.array([
    [88, 92, 75],
    [81, 79, 95]
])

In [204]:
grades2

array([[88, 92, 75],
       [81, 79, 95]])

In [205]:
np.hstack(grades,grades2)

TypeError: hstack() takes 1 positional argument but 2 were given

In [206]:
np.hstack((grades,grades2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [207]:
grades

array([[100,  94,  87,  61],
       [ 61,  60,  87,  80],
       [ 80,  96,  65,  81]])

In [208]:

grades = np.array([
    [90, 85, 78],
    [88, 92, 81]
])

In [209]:
grades

array([[90, 85, 78],
       [88, 92, 81]])

In [210]:
np.hstack((grades,grades2))

array([[90, 85, 78, 88, 92, 75],
       [88, 92, 81, 81, 79, 95]])

In [211]:
np.vstack((grades,grades2))

array([[90, 85, 78],
       [88, 92, 81],
       [88, 92, 75],
       [81, 79, 95]])

<><><><><><><><><><><><><><><><><><><><><><><><><>
                   PANDAS
<><><><><><><><><><><><><><><><><><><><><><><><><>

In [212]:
import pandas as pd