In [1]:
import numpy as np


In [2]:
numbers = np.array([1,2,3,4,5])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([1, 2, 3, 4, 5])

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
num = [x for x in range (21) if x%2 ==0]


In [7]:
print(num)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [8]:
num = [x for x in range (2,21,2)]


In [9]:
print(num)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [12]:
integers = np.array([[1,2,3,],[4,5,6]])

print(integers)

[[1 2 3]
 [4 5 6]]


In [13]:
integers.ndim

2

In [14]:
numbers.ndim

1

In [16]:
integers.shape

(2, 3)

In [18]:
numbers.shape

(5,)

In [19]:
integers.size

6

In [20]:
integers.itemsize

8

In [21]:
for row in integers:
    for column in row:
        print(column, end = ' ')
    print()

1 2 3 
4 5 6 


In [23]:
for i in integers.flat:
    print(i, end = ' ')

1 2 3 4 5 6 

---------------------------------FUNCTION CALLBACK-----------------------


In [6]:
import time
def finished_cooking():
    print("ding dong finished cooking")

In [11]:
def cooking(action):
    print("cooking food for my wife")
   
    for i in range(int(time.sleep(2)),-1):
        print(i,end = "\r")
    action()

In [12]:
cooking(finished_cooking)

cooking food for my wife


TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [15]:
import time

def finished_cooking():
    print("Ding dong! Finished cooking 🍲")

def cooking(action):
    print("Cooking food for my wife...")

    # countdown from 5 to 0
    for i in range(5, -1, -1):   # start at 5, stop at -1
        print(f"Time left: {i}", end="\r")  
        time.sleep(1)  # wait 1 second each time

    print()  # move to next line after countdown
    action() # call the callback

cooking(finished_cooking)


Cooking food for my wife...
Time left: 0
Ding dong! Finished cooking 🍲


In [16]:
import time

def finished_cooking():
    print("Ding dong! Finished cooking 🍲")

def cooking(action):
    print("Cooking food for my wife...")
    for i in range(5, -1, -1):
        print(f"\033[KTime left: {i}", end="\r")
        time.sleep(1)
    print()
    action()

cooking(finished_cooking)


Cooking food for my wife...
Time left: 0
Ding dong! Finished cooking 🍲
